// Copyright 2026 Aravine Zhu
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Public shared Foundation vocabulary for canonical values, identities,
 * lifecycle roots, Problems, and data governance without runtime side effects.
 * @packageDocumentation
 */

export {
  canonicalizeJson,
  snapshotCanonicalJson,
  type CanonicalJsonSnapshot,
  type CanonicalJsonValue,
} from "./canonical-json.js";
export { digestCanonicalJson, type Sha256Digest } from "./digest.js";
export {
  asContentDigest,
  createBootId,
  createActivityId,
  createCanonicalConversationId,
  createCanonicalMessageId,
  createCommunicationCommitId,
  createContinuityEpochId,
  createEvidenceId,
  createHostOwnershipToken,
  createInstallationId,
  createInstanceId,
  createMessagingAccountId,
  createReactionId,
  createSubjectId,
  createUuidV7Id,
  isSha256Hex,
  isUuidV7,
  parseContentDigest,
  parseBootId,
  parseActivityId,
  parseCanonicalConversationId,
  parseCanonicalMessageId,
  parseCommunicationCommitId,
  parseContinuityEpochId,
  parseEvidenceId,
  parseHostOwnershipToken,
  parseInstant,
  parseInstallationId,
  parseInstanceId,
  parseMessagingAccountId,
  parseUuidV7Id,
  parseReactionId,
  parseSubjectId,
  SHA256_HEX_PATTERN,
  UUID_V7_PATTERN,
  formatInstant,
  type Branded,
  type ActivityId,
  type BootId,
  type ContentDigest,
  type ContinuityEpochId,
  type EvidenceId,
  type SubjectId,
  type MessagingAccountId,
  type CanonicalConversationId,
  type CanonicalMessageId,
  type ReactionId,
  type CommunicationCommitId,
  type InstallationId,
  type InstanceId,
  type HostOwnershipToken,
  type UuidV7Id,
  type Instant,
} from "./identity.js";
export type { RetentionClass, Sensitivity } from "./data-governance.js";
export {
  createCapabilityId,
  createContributionId,
  createEffectKindId,
  createEffectOperationId,
  asDurableCodeVersion,
  createMicroSystemId,
  createMicroSystemInstanceId,
  createMessagingPlatformId,
  createProviderId,
  createServiceId,
  createWorkItemId,
  NAMESPACED_ID_PATTERN,
  parseCapabilityId,
  parseContributionId,
  parseEffectKindId,
  parseEffectOperationId,
  parseDurableCodeVersion,
  parseMicroSystemId,
  parseMicroSystemInstanceId,
  parseMessagingPlatformId,
  parseProviderId,
  parseServiceId,
  parseWorkItemId,
  type CapabilityId,
  type ContributionId,
  type EffectKindId,
  type EffectOperationId,
  type DurableCodeVersion,
  type MicroSystemId,
  type MicroSystemInstanceId,
  type MessagingPlatformId,
  type NamespacedId,
  type PackageGenerationId,
  type ProductGenerationId,
  type ProviderId,
  type ServiceId,
  type WorkItemId,
} from "./runtime-identity.js";
export { LIFECYCLE_ROOT_IDS, type LifecycleRootId } from "./lifecycle-root.js";
export { POSTGRES_INTEGER_MAX } from "./numeric.js";
export {
  createProblem,
  createProblemError,
  parseProblem,
  ProblemError,
  type FieldError,
  type Problem,
  type ProblemInit,
  type RetryClass,
} from "./problem.js";
